name = "GridVisualize"
uuid = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "1.7"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GridVisualizeTools = "5573ae12-3b76-41d9-b48c-81d0b6e61cc5"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
CairoMakie = "0.11.3, 0.12"
ColorSchemes = "3"
Colors = "0.12,1"
DocStringExtensions = "0.8,0.9"
ElasticArrays = "1"
ExtendableGrids = "1.7"
GLMakie = "0.9, 0.10"
GeometryBasics = "0.4.1"
GridVisualizeTools = "1.1"
HypertextLiteral = "0.9"
Interpolations = "0.14, 0.15"
IntervalSets = "0.7"
LinearAlgebra = "1.6"
Observables = "0.5"
OrderedCollections = "1"
Plots = "1"
PlutoVista = "0.8.24,1"
Printf = "1.6"
PyPlot = "2"
StaticArrays = "1"
julia = "1.9"


[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoVista = "646e1f28-b900-46d7-9d87-d554eb38a413"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
