name = "GridVisualize"
uuid = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.4.1"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ColorSchemes = "3"
Colors = "0.12"
DocStringExtensions = "^0.8.0"
ElasticArrays = "1"
ExtendableGrids = "0.7,0.8"
GeometryBasics = "0.4.1"
HypertextLiteral = "0.9"
Observables = "0.4"
OrderedCollections = "1"
PkgVersion = "0.1"
StaticArrays = "1"
julia = "1.3"
